### PR TITLE
Adapted to root motion and animation being moved to SoulsFormats

### PR DESCRIPTION
**Pull request by koriandrei**
Related changes in SoulsFormats here: https://github.com/Meowmaritus/SoulsFormats/pull/1

### CODE REVIEW

**Comment by Meowmaritus** [comment]
This is a good ass change, but I added interleaved uncompressed animation + edited some shit so it might take a bit to figure out how to merge this

**Comment by koriandrei** [comment]
Hey,

When do you think you'll be able to push these? I can merge these too.

**Comment by Meowmaritus** [comment]
OK I've pushed the latest changes to both repos

**Comment by koriandrei** [comment]
Hey, I've merged them. What file should I load to see if my changes work fine with interleaved animations?

**Comment by koriandrei** [comment]
The changes made in this branch were added to https://github.com/Meowmaritus/DSAnimStudio/pull/7

**Pull request closed without merging**
